nelmio_api_doc:
    documentation:
        info:
            title: iikoProtokol 
            description: Сервер который позволяет работать с iiko без iikoBiz или iikoCloud.
            version: 0.0.1
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT

    areas: # to filter documented areas
        auth: 
          path_patterns:
             - ^/login # Accepts routes under /api except /api/doc
        default:
          path_patterns:
              - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
